### ISSUE TITLE
i added it to plugins folder and the server fucking died

### ISSUE THREAD

**Issue by c0d3rb0y** [Fangoboyo/primplugin#3]
Kept spamming this error
`17:06:50 [WARNING] [PrimPlugin] Task #5 for PrimPlugin v0.2.6 generated an exception
java.lang.NullPointerException
    at tech.nully.primplug.playerStatManagers.manaManager.manaManager.getMana(manaManager.java:143)
    at tech.nully.primplug.playerStatManagers.manaManager.passiveManaAdder$1.run(passiveManaAdder.java:14)
    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)`

**Comment by c0d3rb0y** [comment]
Plugins on server:
PrimPlugin from out folder
Factions from lib
ProtocolLib (1) from lib

**Comment by Fangoboyo** [comment]
1.) Who are you? Discord username
2.) this plugin is a heavy WIP and half of it isnt even complete yet which is why servers have a seizure running it
